{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "helm-common.fullname" . }}
  labels:
    app: {{ include "helm-common.name" . }}
    chart: {{ include "helm-common.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"

spec:
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
{{- end }}
